eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: check-book-service
  profiles:
    active: dev
  cloud:
    config:
      bus:
        retry:
          max-attempts: 20
          initial-interval: 10000
          max-interval: 15000
        fail-fast: true
        refresh:
          enabled: true
        env:
          enabled: true
    function:
      definition: bookConsumerAndProducer
    stream:
      bindings:
        bookConsumerAndProducer-in-0:
          group: group
          destination: book1
          contentType: application/json
        bookConsumerAndProducer-out-0:
          group: group
          destination: book2
          contentType: application/json