spring:
  cloud:
    function:
      definition: bookConsumerAndProducer
    stream:
      bindings:
        bookConsumerAndProducer-in-0:
          group: group
          destination: book1
          contentType: application/json
        bookConsumerAndProducer-out-0:
          group: group
          destination: book2
          contentType: application/json