server:
  port: 8869
spring:
  application:
    name: store-book-service
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    function:
      definition: bookConsumer
    stream:
      bindings:
        bookConsumer-in-0:
          group: group
          destination: book2
          contentType: application/json