spring:
  cloud:
    function:
      definition: bookConsumer
    stream:
      bindings:
        bookConsumer-in-0:
          group: group
          destination: book2
          contentType: application/json