eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8889
spring:
  zipkin:
    enabled: true
  sleuth:
    sampler:
      probability: 2.0
  profiles:
    active: dev
  application:
    name: client-service
  config:
    import: "optional:configserver:"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server