eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8891
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: "http://localhost:8889"
          predicates:
            - Path=/api/client/**
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG