spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          group: group
          destination: book1
          contentType: application/json

server:
  port: 8881