server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    bus:
      enabled: true
    kafka:
      bootstrap-servers: http://localhost:9092
    config:
      server:
        git:
          uri: https://github.com/Serener-D/JavaAdv
          searchPaths: "/configs/{application}/{profile}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/